# Generated by Django 2.2.2 on 2019-06-18 16:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_job_photo_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='photo_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
