# Generated by Django 2.2.2 on 2019-06-18 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_blog_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='summary',
            new_name='content',
        ),
    ]
