# Generated by Django 2.2.2 on 2019-06-18 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190618_0527'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
